import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./hearder"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
